---
title: "Rebecca Martinez"
author: "Rebecca Martinez"
format:
  pdf:
    documentclass: article
    geometry: margin=1in
    fontsize: 11pt
    toc: false
    number-sections: false
---

# Contact Information
- Goleta, CA  
- rebecca_martinez@ucsb.edu
- martinez.rl@hotmail.com  
- [github.com/RebeccaLMartinez](https://github.com/RebeccaLMartinez)  
- [website](https://rebeccalmartinez.github.io/personal_website/)

# Education
**B.S. Environmental Studies**, UCSB *(Expected 2026)*  
**A.S. Biology**, Allan Hancock College *(2024)*  

# Research Experience
**UCSB-Smithsonian Scholars Program – Peer Mentor**  
*Summer 2024*  
- Led RStudio and data science discussions  
- Supported field research in Santa Cruz Island and Panama  

# Teaching & Mentorship
**Embedded Tutor – Anatomy, Chemistry, Microbiology, Physiology**  
Allan Hancock College, 2022–2024  
- Assisted students in labs and study groups  
- Helped first-gen and non-traditional students succeed  

# Skills
- R / RStudio / Posit Cloud  
- Data visualization  
- Zotero, Microsoft Office, Google Suite  
- Fluent in English and Spanish  

# Honors & Awards
- Dean’s List, Allan Hancock College  
- UCSB-Smithsonian Scholars Program Scholar  
- Hancock Honors Gala Speaker (2024)
